services:
  api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    volumes:
      - ../../api:/app
    env_file: ../../.env
    ports:
      - "8000:80"
    restart: always

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pianontust
      POSTGRES_USER: pianontust
      POSTGRES_PASSWORD: pianontust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
