services:
  ngrok:
    image: ngrok/ngrok:alpine
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    depends_on:
      - caddy
    command: http caddy:80 --url=${NGROK_DOMAIN}
    restart: unless-stopped
    networks:
      - piano
  caddy:
    image: caddy:2
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
      - linebot
    restart: unless-stopped
    networks:
      - piano
    expose:
      - "80"
  db:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 15
      start_period: 5s
    restart: always
    networks:
      - piano
    expose:
      - "5432"
  api:
    build: ./api
    volumes:
      - ./api/app:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    networks:
      - piano
    expose:
      - "8000"
  linebot:
    build: ./linebot
    volumes:
      - ./linebot/app:/app
    environment:
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      NGROK_DOMAIN: ${NGROK_DOMAIN}
    command: "gunicorn -w 3 --threads 8 -b 0.0.0.0:5000 app:app"
    restart: unless-stopped
    networks:
      - piano
    expose:
      - "5000"
  mcp:
    build: ./mcp
    volumes:
      - ./mcp/app:/app
    command: fastmcp run server.py --transport http --host 0.0.0.0 --port 8000
    restart: unless-stopped
    networks:
      - piano
    expose:
      - "8000"
volumes:
  pgdata:
  caddy_data:
  caddy_config:
networks:
  piano: